spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/health_log
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    open-in-view: false

  data.rest:
    base-path: /api
    default-page-size: 10

  security:
    user:
      name: beomu
      password: 1234
