spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    open-in-view: false

  sql.init.mode: never
  data.rest:
    base-path: /api
    default-page-size: 10

  security:
    user:
      name: beomu
      password: 1234
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  redis:
    host: localhost
    port: 6379
  session.store-type: redis

---

spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/health_log
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
