spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/health_log
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true

  data.rest:
    base-path: /api
    default-page-size: 10
